sonar.projectKey=eco_tracker
sonar.projectName=EcoTracker
sonar.projectVersion=1.0
sonar.sources=eco_tracker
sonar.tests=eco_tracker
sonar.inclusions=eco_tracker/**/*.py
sonar.test.inclusions=eco_tracker/**/test_*.py,eco_tracker/**/*_test.py
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqa_24ff9cc7921c02cd7fab480ddc716c85baf9b89a
sonar.python.coverage.reportPaths=coverage.xml
