/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BarChart: typeof import('./components/BarChart.vue')['default']
    CalculateEmissionsTemp: typeof import('./components/CalculateEmissionsTemp.vue')['default']
    CategoryFilter: typeof import('./components/CategoryFilter.vue')['default']
    ConfidenceSlider: typeof import('./components/ConfidenceSlider.vue')['default']
    DataFilterGroup: typeof import('./components/DataFilterGroup.vue')['default']
    DataFilters: typeof import('./components/DataFilters.vue')['default']
    DateFilter: typeof import('./components/DateFilter.vue')['default']
    EmissionMetrics: typeof import('./components/EmissionMetrics.vue')['default']
    EmissionsOverTime: typeof import('./components/EmissionsOverTime.vue')['default']
    EmissionsPerCategory: typeof import('./components/EmissionsPerCategory.vue')['default']
    FailedStepsTable: typeof import('./components/FailedStepsTable.vue')['default']
    FetchDataButton: typeof import('./components/FetchDataButton.vue')['default']
    FilterDataButton: typeof import('./components/FilterDataButton.vue')['default']
    HelloWorld: typeof import('./components/WelcomeText.vue')['default']
    NoResults: typeof import('./components/NoResults.vue')['default']
    PieChart: typeof import('./components/PieChart.vue')['default']
    ProductDetailsTable: typeof import('./components/ProductDetailsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopEmittingProducts: typeof import('./components/TopEmittingProducts.vue')['default']
    WelcomeText: typeof import('./components/WelcomeText.vue')['default']
  }
}
