/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CalculateEmissionsTemp: typeof import('./components/CalculateEmissionsTemp.vue')['default']
    HelloWorld: typeof import('./components/WelcomeText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomeText: typeof import('./components/WelcomeText.vue')['default']
  }
}
